name: 'Gate for validation'

on: workflow_call

jobs:
  gate:
    runs-on: ubuntu-latest
    name: 'Seek for changed source files'
    outputs:
      changed: ${{ steps.changed.outputs.src }}
    steps:
      - name: Check source file
        uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            src:
              - 'src/**'
