name: publishing

on: [workflow_dispatch]

env:
  BACKEND_DIRECTORY: ./src/backend
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run_integration_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: keebox_db
        ports:
          - 5432:5432

    steps:
      - name: checkout project
        uses: actions/checkout@v2

      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: running integration tests
        run: dotnet test ${{ env.BACKEND_DIRECTORY }} --filter "TestCategory~Integration"

  publish_images:
    runs-on: ubuntu-latest

    needs:
      - run_integration_tests

    steps:
      - name: checkout project
        uses: actions/checkout@v2

      - name: extract version
        run: |
          temp_version=$( cat ${{ env.BACKEND_DIRECTORY }}/ProductSettings.cs | grep -oP '(?<=AssemblyVersion\(\")[\d\w-\.]*(?=\")' );
          echo "VERSION=$temp_version" >> $GITHUB_ENV;

      - name: log to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push secret service
        uses: docker/build-push-action@v1
        with:
          file: ${{ env.BACKEND_DIRECTORY }}/SecretsService/Dockerfile
          context: ${{ env.BACKEND_DIRECTORY }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
