name: publish

on: [workflow_dispatch]

env:
  BACKEND_DIRECTORY: ./src/backend

jobs:
  run_integration_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ralfred_db
        ports:
          - 5432:5432

    steps:
      - name: checkout project
        uses: actions/checkout@v2

      - name: setting up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: running integration tests
        run: dotnet test ${{ env.BACKEND_DIRECTORY }} --filter "TestCategory~Integration"
