name: Unit tests

on:
  - pull_request
  - workflow_call

jobs:
  gate:
    name: Run unit tests
    uses: keebox/keebox/.github/workflows/gate.yml@master

  backend:
    runs-on: ubuntu-latest
    name: 'Run unit tests'

    needs: gate
    if: ${{ needs.gate.outputs.changed == 'true' || github.event_name == 'workflow_call' }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run unit tests
        run: |
          for test_dir in src/*.UnitTests; do
            dotnet test --no-restore --no-build --filter "TestCategory!~Integration" --results-directory=${{ github.workspace }}/test-results $test_dir;
          done;
